# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:


  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer2.org1.example.com

  

  
